### ISSUE TITLE
Fails to update db on windows (strawberry perl)

### ISSUE THREAD

**Issue by akauste** [DrHyde/perl-modules-IP-World#1]
On windows 10, strawberry perl 5.20.1, installed with berrybrew, I get this error when running maint_ip_world_db:
List form of pipe open not implemented at C:\berrybrew\5.20.1_64\perl\site\bin/maint_ip_world_db line 128

On windows 10, strawberry perl 5.24.1, installed with berrybew, I get this error when running main_ip_world_db:
Can't open C:\berrybrew\5.24.1_64\perl\site\lib\auto\IP\World/worldip.en.text.zip for read: No such file or directory at C:\berrybrew\5.24.1_64\perl\site\bin/maint_ip_world_db line 128

**Comment by DrHyde** [comment]
Thanks for letting me know.

Can you confirm that you're using the latest version of IP::World from the CPAN, and that you have 'unzip' installed? I'd expect 5.24.1 to fail something like that if unzip isn't available. It's a bit of a misleading error message.

The list form of pipe open wasn't implemented on Windows until perl 5.22, so I suppose I should fix that. On the other hand, Laziness compels me to ask if you actually need it on 5.20, cos as far as I know you're the first person to care in however many years it is since IP::World was released :-) Bear in mind that 5.20 goes completely out of p5p support soon anyway - and even then, it's only 5.20.*2* that's currently supported at all.

**Comment by akauste** [comment]
Thanks for the quick reply! You're right, unzip was missing and now the script works with 5.24 and that's good enough for me. I've been using 5.20 to match the current debian stable, but no need for any extra work for that, when it works with the newest perl on windows too.

**Comment by DrHyde** [comment]
Hurrah! I'll close the issue then.
